# Generated by Django 4.2.7 on 2025-12-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_processor', '0005_fix_health_score_decimal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
